### PR TITLE
Update Django/Python versions in Automated Tests

### PR DESCRIPTION
**Pull request by jmoppel**
Updated the automated tests run by Github Actions to only use supported
versions and combinations of Python and Django.

- Added Python 3.10 to Github automated tests for Django 3.2 and 4.0.
- Removed Python 3.6 and Django 2.2/3.1 from tests {deprecated upstream).
- Run linters using the latest version of Python (3.10).
- Fix test suite so it passes (incorrect results file)

### CODE REVIEW

**Comment by jmoppel** [comment]
Apologies for accidentally closing #99! That was my first time using Github Pull Requests. I will submit another PR to replace #99 once this request has been merged.

**Comment by smithdc1** [comment]
Thanks for this. This looks good to me. 

I think just one amend needed before I merge this. Could you also update the `setup.py` file. In particular the `python_requires` setting, but would be useful to update the classifiers as well. 

https://github.com/django-crispy-forms/crispy-bootstrap5/blob/2b1a014d1630dc958c7b9ea72605580e14684693/setup.py#L36

As a bonus, I'd also take dropping Django 2.2 at this stage if you wanted update for that as well?

**Comment by jmoppel** [comment]
I made all the changes you suggested, including removing Django 2.2 and updating the classifiers. Would you also like for me to update publish.yml too, since it has references to Python 3.6? I'm not 100% certain what all that workflow does, so I felt it would be better to check with you first. I'm happy to add publish.yml to this PR or to create a new one -- whichever you'd prefer. Thanks!

**Comment by smithdc1** [comment]
> . Would you also like for me to update publish.yml too, since it has references to Python 3.6? 

Yes please, let's do that here as well.

Thank you!!

**Comment by jmoppel** [comment]
Ok, everything we discussed is complete. Please let me know if there's anything else needed before merging. Thanks!

**Comment by smithdc1** [comment]
Hi @jmoppel -- could you pull your other changes into here so we can get the test suite to pass? 

https://github.com/django-crispy-forms/crispy-bootstrap5/runs/5504213317?check_suite_focus=true#step:6:61

**Comment by jmoppel** [comment]
Done. All tests and linting actions now finish without errors on my fork.
https://github.com/jmoppel/crispy-bootstrap5/actions/runs/1982978715

**Comment by smithdc1** [comment]
@jmoppel  thanks for all of your efforts. 🏅

**Pull request merged**
