### PR TITLE
 Fixed offset class of checkbox in form horizontal

### PR DESCRIPTION
**Pull request by lauri-openscop**
A tricky way to apply the right offset class on checkbox field whitout touching the core application..

### CODE REVIEW

**Comment by smithdc1** [comment]
Thanks! Glad you found a way of including it in this template pack. 🏅

Could I ask you to add tests for this? See the link below for how we are writing new tests. 

https://github.com/django-crispy-forms/crispy-bootstrap5/pull/44

**Comment by lauri-openscop** [comment]
I have updated test_label_class_and_field_class_bs5_offset_when_horizontal to work with the current offset. Is that good for you ?

**Comment by smithdc1** [comment]
Thanks for this. I think this is close but it doesn't work where the number of columns is two digits. i.e. `col-lg-12` would become `offset-lg-1`. 

I was wondering if we could refactor `bootstrap_checkbox_offsets` in core to be a list/dict(?) of size and number of columns. We could then build the string in the template rather than code as the particular format here seems to change with each major bootstrap release. 

What do you think?

**Comment by lauri-openscop** [comment]
My bad, it was cause by the slice. I didn't think about two digit columns. 
I think that if we have to change the core application the best would be to change helper.py like i said in  https://github.com/django-crispy-forms/crispy-bootstrap5/issues/49#issuecomment-845959633 or something like that. What do you think ?

**Comment by smithdc1** [comment]
I think that github asking folk to approve each test run is a bit tiresome (I mean, once would be ok for this PR, but I've pressed it countless times for this PR alone as we've been itterating through the problem!). 

As for this patch itself I think it's fine. Let's have this. 👍

**Pull request merged**
