### PR TITLE
Update field_with_buttons.html

### PR DESCRIPTION
**Pull request by digitalfox**
Add missing form-label class

### CODE REVIEW

**Comment by smithdc1** [comment]
Thanks. Could you add a test? See #36 for how were currently building tests.

**Comment by digitalfox** [comment]
@smithdc1 is it ok for you ?

**Comment by smithdc1** [comment]
Thanks for your continued efforts here. 👍

Could we amend the test to test the whole form? It should be "just" a case of putting the `html` that is in your test into a HTML file and then your assert line can be something like this.

https://github.com/django-crispy-forms/crispy-bootstrap5/blob/78981e7158b7f60409ba26314464e01a0e76ef7a/tests/test_layout.py#L564

Most of the tests here come from bootstrap4 which were written with partial coverage in code which has been an issue for a long time. We're _slowly_ trying to move to this new method which I'm hoping is more maintainable.

**Comment by smithdc1** [comment]
Hi @digitalfox -- I finally got time to sit down with this properly. I think this layout object is one I've not looked at in detail yet. I've pushed a few amends to make it work with bootstap5 button-addons (see link below). 

There is also a need to fix the input size for this object but that's a patch for crispy-forms core. 

Let me know what you think? 


https://getbootstrap.com/docs/5.0/forms/input-group/#button-addons

**Comment by digitalfox** [comment]
Thanks for the merge. Sorry, I did not have time to have a look. I hope to be able to test it next month.

**Pull request merged**
