### PR TITLE
Added tox config and used in GHA workflows

### PR DESCRIPTION
**Pull request by smithdc1**
Tests currently failing on latest version of crispy-forms. Will investigate that as a separate PR.

### CODE REVIEW

**Comment by smithdc1** [comment]
This doesn't seem right. I don't think it's running the tests for crispy-forms 1.x

**Review by carltongibson — APPROVED** [review]
Looks good.

**Comment by smithdc1** [comment]
Hmm. So this works locally now, but isn't running at all here. Is this one of those cases where I need to merge it first? 🤔

**Comment by smithdc1** [comment]
Closing and reopening the PR seemed to kick it back into life 🤷 

Thanks!

**Pull request merged**
