### PR TITLE
Fixes #14 -- Added Float Field

### LINKED ISSUE #14: Floating labels -- Alpha 3
Alpha 3 adds floating labels -- 
https://v5.getbootstrap.com/docs/5.0/forms/floating-labels/

Think this needs a small template change and then some docs to explain how to add the extra class. 

- Add class via `wrapper_class="form-floating"`

- Can this line be moved up above the label -- that is the `label` and `input` sit along side each other within the same `div`? :thinking: 

https://github.com/django-crispy-forms/crispy-bootstrap5/blob/856b7dbbba91a761a352d4de3fd6e424f8a38175/crispy_bootstrap5/templates/bootstrap5/field.html#L41

### PR DESCRIPTION
**Pull request by smithdc1**
@millerthegorilla -- here's a draft implementation for floating fields. Do you want to take a look?

The test shows how this would be used. Is this the right way of doing this? 🤔

### CODE REVIEW

**Review by millerthegorilla — COMMENTED** [review]
Hi, that is not working for me, but I had to change the template to include bootstrap4.
```
 {% include 'bootstrap4/layout/help_text_and_errors.html' %}
```
I am missing the label.

**Comment by smithdc1** [comment]
@millerthegorilla -- anything else to add here?

If not I'll write up a small documentation note -- probably to the readme -- and look to merge this.

**Comment by millerthegorilla** [comment]
I will take a look first thing tomorrow, but I still haven't got round to switching my project to crispy bs5 yet.

**Comment by eriktelepovsky** [comment]
Perfect! Looking forward to merge this.

**Comment by smithdc1** [comment]
@eriktelepovsky Have you given this a run? Do you think the way this would be used in forms is right?

**Comment by millerthegorilla** [comment]
Hi, sorry I got snowed under.  I just checked this and it looks really good, and works well, at first glance.  Looking forward to it being merged.

**Comment by millerthegorilla** [comment]
Just one thing I notice straight away, probably me not getting it straight, but there are a few floating fields in a form, that have the following below them - <small id="hint_id_display_name" class="form-text text-muted">display name</small>
I guess this is from help_text_and_errors, but I don't have help text defined for those floating fields that have this hint text, and not all the floating fields are displaying a hint.
I have added help_text to the model field that is displayed and cannot see the help text in the form using 'floatingfield'.  However, I've been away from django for a month, and am just warming up to it again.  I will return first thing tomorrow, and take a closer look at where I might be going wrong.

**Comment by smithdc1** [comment]
Ok, let's merge this. Thanks all for your input. 

>The only issue that I can see is that when I have help_text defined in the model rather than the form, it is not showing in the rendered html. 

This sounds like a separate issue, I'm not sure without taking a closer look

**Comment by millerthegorilla** [comment]
I haven't tested selects, but it also works fine with textareas which is nice.

**Comment by millerthegorilla** [comment]
Hey @smithdc1 ,  when is the merge with main likely to happen?  I am hoping to roll out the bootstrap5 branch of my site.  Thanks,

**Comment by millerthegorilla** [comment]
@smithdc1 is there any reason this can't be merged?  I am hoping to roll out my crispy forms bootstrap5 site, with the funky new floatfields!

**Comment by smithdc1** [comment]
Ok, I added additional tests for failing fields, text area and selects. All seem to look ok to me. 🙂

**Pull request merged**
