### PR TITLE
Fix the headers of table_inline_formset.html do not display correctly 

### LINKED ISSUE #139: The headers of `table_inline_formset.html` do not display correctly
The headers of the table do not display correctly using the `table_inline_formset.html` template to render a inline formset 

imagen

### PR DESCRIPTION
**Pull request by blasferna**
The headers of the table do not display correctly using the table_inline_formset.html template to render a inline formset

**Before**

imagen

**After**

imagen

fix #139

### CODE REVIEW

**Comment by smithdc1** [comment]
Thanks for the patch. 

Could you add a small test? A minimal layout could be created with the output asserted something like this. 

https://github.com/django-crispy-forms/crispy-bootstrap5/blob/94f0ca5adbe528b7ea43ab8238e4adc849ae84a3/tests/test_layout_objects.py#L366

**Comment by blasferna** [comment]
Can I edit the existing test for `bootstrap5/table_inline_formset.html`? Because I see that it fails with the changes I have introduced in this pull request. Or would you prefer a new test?

**Comment by smithdc1** [comment]
Yes. Fixing the failing test would be great. 

Hopefully the tests run this time when you push the changes. 🤞

**Comment by smithdc1** [comment]
Thank you! 🥇

**Pull request merged**
