### PR TITLE
Fixed InlineField()

### LINKED ISSUE #25: Inline fields don't seem to display correctly
I was able to fix it by overriding the template `bootstrap5/layout/inline_field.html` with the following.

```
{% load crispy_forms_field %}

{% include 'bootstrap5/field.html' with label_class='visually-hidden' %}
```

### PR DESCRIPTION
**Pull request by smithdc1**
Fixes #25 

@epicserve -- Would you like to take a look at this? I like your patch, it's very simple, but it doesn't add in the placeholders (which we have on the bs4 pack).

### CODE REVIEW

**Comment by epicserve** [comment]
@smithdc1,

Looks good to me. Nothing jumped out at me as being wrong. If you wanted to make a release with this, I would be happy to use it in our BS5 upgrade branch.

**Comment by smithdc1** [comment]
Thanks for the quick response. :+1: 

I'll have a go at a release later... I want to try and get the automated release process working to make it easier in the future. I _think_ it should "just work" but....  :shrug:

**Comment by epicserve** [comment]
@smithdc1,

I randomly found this project and you could see how they do it.

https://github.com/jazzband/django-formtools/blob/master/.github/workflows/release.yml

**Comment by smithdc1** [comment]
https://pypi.org/project/crispy-bootstrap5/ ok, a new release is now available on PyPI.

**Comment by epicserve** [comment]
@smithdc1,

I'll try it tomorrow. BTW, how do you trigger a release event. I was looking at.
https://github.com/django-crispy-forms/crispy-bootstrap5/blob/master/.github/workflows/publish.yml

**Comment by smithdc1** [comment]
It's triggered by creating a 'release' on GitHub. I've linked below the item I created which triggered this workflow. It also created the version tag for me.  

First time I did it this way and it seemed to work well. 

https://github.com/django-crispy-forms/crispy-bootstrap5/releases

**Comment by epicserve** [comment]
@smithdc1,

Did you create this commit manually or does creating a release add the commit?
https://github.com/django-crispy-forms/crispy-bootstrap5/commit/81f458f479a00b5ee8026effe0656e10465a576e

**Comment by epicserve** [comment]
@smithdc1,

Also, I tested this and it seems to work, however it adds the class "field.html" is that a crispy-forms thing or BS5 thing or a bug? It doesn't seem correct to have CSS class with a period in the name.

```
<div id="div_id_first_name" class="field.html">
  <label for="id_first_name" class="visually-hidden">
      First name
  </label>
  <input type="text" name="first_name" value="Brent" maxlength="150" class="textinput textInput form-control" placeholder="First name" id="id_first_name">            
</div>
```

**Comment by smithdc1** [comment]
@epicserve 

>Did you create this commit manually or does creating a release add the commit? 81f458f

I created the commit manually -- then the release manually. (Would be nice if it was a one-time thing!)

>Also, I tested this and it seems to work, however it adds the class "field.html" is that a crispy-forms thing or BS5 thing or a bug? It doesn't seem correct to have CSS class with a period in the name.

The `field.html` in the class looks very odd to me, it's certainly not intended! I'm not quite sure what is going on here as it seems odd to get the file name into the class!

In my small [test](https://github.com/django-crispy-forms/crispy-bootstrap5/blob/master/tests/results/test_bootstrap5_form_inline.html),  I don't see this happening. Are you able to share a small example so I can reproduce the bug?

**Comment by epicserve** [comment]
@smithdc1,

Regarding deployment ... I wrote this deployment script that does everything. The only drawback is that you would have to run it locally.

https://gist.github.com/epicserve/2f0a2f270c8c78119cab44247f6339e6

Regarding `feild.html` it looks like that was an issue with my custom templatetag, so please disregard my comment.

**Comment by smithdc1** [comment]
Thanks for the quick feedback. 👍

**Pull request merged**
